import {Router} from 'express'; import {prisma} from '../../config/database.js'; import {authenticate} from '../../middleware/authenticate.js'; import {requirePermission} from '../../middleware/authorize.js'; import {z} from 'zod';
const r=Router(); r.use(authenticate); const candidate=async id=>prisma.candidateProfile.findUnique({where:{userId:id},select:{id:true}});
r.get('/profile',async(req,res,next)=>{try{const data=await prisma.candidateProfile.findUnique({where:{userId:req.user.id},include:{skills:{include:{skill:true}},education:true,experience:true,resumes:true}});res.json({success:true,message:'Candidate profile retrieved',data});}catch(e){next(e);}});
const cp=z.object({headline:z.string().max(200).nullable().optional(),experienceYears:z.number().min(0).max(80).nullable().optional(),expectedSalary:z.number().min(0).nullable().optional(),noticePeriod:z.string().max(80).nullable().optional(),preferredLocation:z.string().max(200).nullable().optional(),githubUrl:z.string().url().nullable().optional(),linkedinUrl:z.string().url().nullable().optional(),portfolioUrl:z.string().url().nullable().optional()}).strict().refine(x=>Object.keys(x).length>0);
r.patch('/profile',requirePermission('PROFILE','UPDATE'),async(req,res,next)=>{try{const p=await candidate(req.user.id);if(!p) return res.status(404).json({success:false,message:'Candidate profile not found.',code:'NOT_FOUND'});const data=cp.parse(req.body);const out=await prisma.candidateProfile.update({where:{id:p.id},data});res.json({success:true,message:'Candidate profile updated',data:out});}catch(e){next(e);}});
r.post('/experience',requirePermission('PROFILE','UPDATE'),async(req,res,next)=>{try{const p=await candidate(req.user.id);const d=z.object({companyName:z.string().min(1).max(200),jobTitle:z.string().min(1).max(160),employmentType:z.string().max(80).optional(),startDate:z.coerce.date().optional(),endDate:z.coerce.date().optional(),isCurrent:z.boolean().optional(),description:z.string().max(5000).optional()}).strict().parse(req.body);const data=await prisma.candidateExperience.create({data:{...d,candidateId:p.id}});res.status(201).json({success:true,message:'Experience created',data});}catch(e){next(e);}});
for (const [path,model] of [['education','candidateEducation'],['experience','candidateExperience']]) { const schema=path==='education'?z.object({institution:z.string().min(1).max(200),degree:z.string().max(160).nullable().optional(),fieldOfStudy:z.string().max(160).nullable().optional(),startDate:z.coerce.date().nullable().optional(),endDate:z.coerce.date().nullable().optional(),grade:z.string().max(80).nullable().optional(),description:z.string().max(5000).nullable().optional()}).strict():z.object({companyName:z.string().min(1).max(200).optional(),jobTitle:z.string().min(1).max(160).optional(),employmentType:z.string().max(80).nullable().optional(),startDate:z.coerce.date().nullable().optional(),endDate:z.coerce.date().nullable().optional(),isCurrent:z.boolean().optional(),description:z.string().max(5000).nullable().optional()}).strict(); if(path==='education')r.post('/education',requirePermission('PROFILE','UPDATE'),async(req,res,next)=>{try{const p=await candidate(req.user.id);const d=schema.parse(req.body);const data=await prisma.candidateEducation.create({data:{...d,candidateId:p.id}});res.status(201).json({success:true,message:'Education created',data});}catch(e){next(e);}});r.patch(`/${path}/:id`,requirePermission('PROFILE','UPDATE'),async(req,res,next)=>{try{const p=await candidate(req.user.id);const data=await prisma[model].updateMany({where:{id:req.params.id,candidateId:p.id},data:schema.parse(req.body)});if(!data.count)throw Object.assign(new Error('Record not found.'),{status:404,code:'NOT_FOUND'});res.json({success:true,message:`${path} updated`});}catch(e){next(e);}});r.delete(`/${path}/:id`,requirePermission('PROFILE','UPDATE'),async(req,res,next)=>{try{const p=await candidate(req.user.id);const d=await prisma[model].deleteMany({where:{id:req.params.id,candidateId:p.id}});if(!d.count)throw Object.assign(new Error('Record not found.'),{status:404,code:'NOT_FOUND'});res.json({success:true,message:`${path} deleted`});}catch(e){next(e);}}); }
r.post('/skills',requirePermission('PROFILE','UPDATE'),async(req,res,next)=>{try{const {name}=z.object({name:z.string().trim().min(1).max(120)}).parse(req.body);const p=await candidate(req.user.id);let skill=await prisma.skill.findFirst({where:{name:{equals:name,mode:'insensitive'}}});if(!skill)skill=await prisma.skill.create({data:{name}});await prisma.candidateSkill.create({data:{candidateId:p.id,skillId:skill.id}});res.status(201).json({success:true,message:'Skill added',data:skill});}catch(e){next(e);}});
r.delete('/skills/:skillId',requirePermission('PROFILE','UPDATE'),async(req,res,next)=>{try{const p=await candidate(req.user.id);await prisma.candidateSkill.deleteMany({where:{candidateId:p.id,skillId:req.params.skillId}});res.json({success:true,message:'Skill removed'});}catch(e){next(e);}});
r.post('/resume',requirePermission('PROFILE','UPDATE'),async(req,res,next)=>{try{const d=z.object({fileName:z.string().min(1).max(255),fileUrl:z.string().url(),storageKey:z.string().min(1).max(500),mimeType:z.string().min(1).max(120),fileSize:z.coerce.bigint().positive()}).parse(req.body);const p=await candidate(req.user.id);const data=await prisma.$transaction(async tx=>{await tx.resume.updateMany({where:{candidateId:p.id,isCurrent:true},data:{isCurrent:false}});return tx.resume.create({data:{...d,candidateId:p.id,isCurrent:true}});});res.status(201).json({success:true,message:'Resume metadata saved',data});}catch(e){next(e);}});
r.delete('/resume/:id',requirePermission('PROFILE','UPDATE'),async(req,res,next)=>{try{const p=await candidate(req.user.id);await prisma.resume.deleteMany({where:{id:req.params.id,candidateId:p.id}});res.json({success:true,message:'Resume metadata deleted'});}catch(e){next(e);}});
export default r;
