import {prisma} from '../../config/database.js';
import {AppError} from '../../middleware/errorHandler.js';
import {PUBLIC_ROLES} from './auth.constants.js';
import {generateAccessToken,generateRefreshToken,hashPassword,hashToken,refreshExpiry,verifyPassword} from './auth.utils.js';
const safeUserSelect={id:true,email:true,status:true,profile:{select:{firstName:true,lastName:true}},roles:{select:{role:{select:{name:true}}}}};
const mapUser=u=>({id:u.id,email:u.email,roles:u.roles.map(x=>x.role.name),profile:u.profile?{firstName:u.profile.firstName,lastName:u.profile.lastName}:null});
async function createSession(tx,userId){const raw=generateRefreshToken();await tx.refreshToken.create({data:{userId,tokenHash:hashToken(raw),expiresAt:refreshExpiry()}});return raw;}
export async function register(input){
 const email=input.email.trim().toLowerCase();if(!PUBLIC_ROLES.includes(input.role))throw new AppError(403,'ROLE_NOT_ALLOWED','This role cannot be selected during public registration.');
 if(input.role==='RECRUITER'&&input.companyId&&!await prisma.company.findUnique({where:{id:input.companyId},select:{id:true}}))throw new AppError(400,'INVALID_COMPANY','The selected company does not exist.');
 const passwordHash=await hashPassword(input.password);
 try {const result=await prisma.$transaction(async tx=>{const role=await tx.role.findUnique({where:{name:input.role},select:{id:true}});if(!role)throw new AppError(500,'ROLE_NOT_CONFIGURED','Registration role is not configured.');const user=await tx.user.create({data:{email,passwordHash,profile:{create:{firstName:input.firstName,lastName:input.lastName,phone:input.phone}},roles:{create:{roleId:role.id}},...(input.role==='CANDIDATE'?{candidateProfile:{create:{}}}:{recruiterProfile:{create:{companyId:input.companyId}}})},select:safeUserSelect});const refreshToken=await createSession(tx,user.id);return {user,refreshToken};});return {user:mapUser(result.user),accessToken:generateAccessToken(result.user.id),refreshToken:result.refreshToken};}catch(e){if(e.code==='P2002')throw new AppError(409,'EMAIL_EXISTS','An account with this email already exists.');throw e;}
}
export async function login(input){const email=input.email.trim().toLowerCase();const user=await prisma.user.findUnique({where:{email},select:{id:true,passwordHash:true,status:true,...safeUserSelect}});if(!user||user.status!=='ACTIVE'||!(await verifyPassword(input.password,user.passwordHash)))throw new AppError(401,'INVALID_CREDENTIALS','Email or password is incorrect.');const refreshToken=await prisma.$transaction(async tx=>{await tx.user.update({where:{id:user.id},data:{lastLoginAt:new Date()}});return createSession(tx,user.id);});return {user:mapUser(user),accessToken:generateAccessToken(user.id),refreshToken};}
export async function refresh(rawToken){if(!rawToken)throw new AppError(401,'INVALID_REFRESH_TOKEN','Refresh token is invalid or expired.');const tokenHash=hashToken(rawToken);return prisma.$transaction(async tx=>{const stored=await tx.refreshToken.findUnique({where:{tokenHash},select:{id:true,userId:true,expiresAt:true,revokedAt:true,user:{select:{status:true}}}});if(!stored||stored.revokedAt||stored.expiresAt<=new Date()||stored.user.status!=='ACTIVE')throw new AppError(401,'INVALID_REFRESH_TOKEN','Refresh token is invalid or expired.');const revoked=await tx.refreshToken.updateMany({where:{id:stored.id,revokedAt:null},data:{revokedAt:new Date()}});if(!revoked.count)throw new AppError(401,'INVALID_REFRESH_TOKEN','Refresh token is invalid or expired.');const next=await createSession(tx,stored.userId);return {accessToken:generateAccessToken(stored.userId),refreshToken:next};});}
export async function logout(rawToken){if(rawToken)await prisma.refreshToken.updateMany({where:{tokenHash:hashToken(rawToken),revokedAt:null},data:{revokedAt:new Date()}});}
export async function logoutAll(userId){await prisma.refreshToken.updateMany({where:{userId,revokedAt:null},data:{revokedAt:new Date()}});}
export async function currentUser(userId){const user=await prisma.user.findUnique({where:{id:userId},select:{...safeUserSelect,emailVerified:true,candidateProfile:{select:{id:true,headline:true,experienceYears:true,preferredLocation:true}},recruiterProfile:{select:{id:true,designation:true,department:true,company:{select:{id:true,name:true}}}}}});if(!user||user.status!=='ACTIVE')throw new AppError(401,'UNAUTHENTICATED','Authentication required.');return {...mapUser(user),emailVerified:user.emailVerified,candidateProfile:user.candidateProfile,recruiterProfile:user.recruiterProfile};}
export async function changePassword(userId,input){const user=await prisma.user.findUnique({where:{id:userId},select:{passwordHash:true}});if(!user||!(await verifyPassword(input.currentPassword,user.passwordHash)))throw new AppError(400,'CURRENT_PASSWORD_INVALID','Current password is incorrect.');if(input.currentPassword===input.newPassword)throw new AppError(400,'PASSWORD_UNCHANGED','New password must differ from the current password.');const passwordHash=await hashPassword(input.newPassword);await prisma.$transaction(async tx=>{await tx.user.update({where:{id:userId},data:{passwordHash}});await tx.refreshToken.updateMany({where:{userId,revokedAt:null},data:{revokedAt:new Date()}});});}
